### PR TITLE
delete unneeded code

### PR DESCRIPTION
**Pull request by garymm**

### CODE REVIEW

**Comment by rcoreilly** [comment]
Definitely don't delete lvis objrec and probably others - I'm not able to review full list but probably most of those should be kept. Can add local go.mod to keep them working while updating global go.mod - and the they can be updated as needed. These are important test cases.  Can add a ticket to update them.

**Comment by garymm** [comment]
Changed to keep lvis and objrec.

**Comment by qemqemqem** [comment]
What's the purpose of deleting this code? I'm not actively using it but it's experimental work that we've done in the past. 

Is it broken?

**Comment by garymm** [comment]
It's not broken. If it's useful to keep at tip of master we can keep it.
If it's unlikely to be read or modified soon I think we should delete it. Having unused code makes thing:
* Slower to build and test
* Noisier search results when searching in the repo
* Slower to git clone
* Harder to find out what's important / up to date from reading the code

And we can always go into the history to find it.

**Comment by rcoreilly** [comment]
also keep one2many, text_one2many, mechs/simple_supervised, and @wumpusman probably want's to weigh in on some of these.

new team members may want to explore some of these things.  

In general I think it is hard to go back in history and find something -- like digging through the trash, there is so much stuff, it is hard to know what's what.  so if anything is at all likely to be relevant going forward, I think it is better to err on the side of keeping it.

**Comment by garymm** [comment]
What's the value of keeping these specifically vs the many examples in the axon repo?

**Comment by rcoreilly** [comment]
In general these are integrated with the obelisk infrastructure, and also explore important test cases that are not elsewhere (one2many).

Ideally, `mechs` should comprise a set of systematic tests that validate the capabilities of the algorithm and can be used for testing new ideas as they are developed..

**Comment by rcoreilly** [comment]
I can't tell what that latest commit is relative to the original -- just shows what looks like the same things being deleted again?  anyway, please do not delete *one2many.

**Review by wumpusman — COMMENTED** [review]
The files outside of one2many, and simple model are fine to delete imo (some of which I did), since they are not pertinent to immediate use cases, or show how to run axon in conjunction with obelisk.

**Comment by garymm** [comment]
There's a lot of things named "simple" so I'm not sure exactly what you mean by "simple model", but I'm not deleting models/integrated/simple_supervised, which is my best guess as to what is worth keeping.

@rcoreilly the only one2many files being deleted have an ".old" suffix which to me seems like a circa 2002 version control scheme. 

Can someone please take another look?

**Review by wumpusman — COMMENTED** [review]
Leave the one2many directory, and leave the simple_supervised directory.

**Pull request merged**
