### PR TITLE
sort python imports with isort

### PR DESCRIPTION
**Pull request by garymm**
Also enforce this in the GitHub check.

Instructions for editor integration: https://github.com/PyCQA/isort/wiki/isort-Plugins

### CODE REVIEW

**Comment by siboehm** [comment]
Should probably be `isort --profile black` see: https://pycqa.github.io/isort/docs/configuration/black_compatibility.html

May be useful to setup black and isort it via pre-commit instead, so we have a good way of running the checks & formatters locally via the same parameters

**Comment by garymm** [comment]
> Should probably be isort --profile black 

That's specified in `pyproject.toml`.

I'll file a bug to look into pre-commit. Feel free to take it if you want.

**Comment by qemqemqem** [comment]
I don't mind sorting them like this every so often, but I'd rather it not be something that interferes with pushes in the future like a pre-commit.

**Review by qemqemqem — APPROVED** [review]

**Comment by garymm** [comment]
@qemqemqem would you be OK with configuring your editor to sort them automatically on save?

Then it's a one-time cost of <10 minutes for every developer, rather than having to do separate clean-up PRs.

I think this should work for PyCharm: https://plugins.jetbrains.com/plugin/15434-isortconnect

**Review by wumpusman — APPROVED** [review]
I'm fine with this, is this just so we have imports sorted in a consistent way?

**Comment by garymm** [comment]
@wumpusman yes, just for consistency.

**Pull request merged**
