### PR TITLE
remove axon, emergent submodules, remove go.work

### PR DESCRIPTION
**Pull request by rcoreilly**
You should remove ./axon and ./emergent from your go.work file after updating to this.

This was a pretty annoying process due to the removal of emergent/agent at some point, which old versions of axon were still referring to, and for some unknown reason, go mod tidy insisted on trying to use those old versions somewhere.

So I just updated everything to the latest axon 1.5.1, even if it might spew some garbage about params not being relevant in some models.

protobrain loads without param errs with my updates, but the gui seems to not run by default so I don't know if it is actually working reasonably.

lvis and objrec are more self-contained and have their own tidy little go.mods so they should continue to work in perpetuity.

Due to the fact that worlds import from models (and vice-versa??) there are interdependencies, which should ideally be removed at some point.  This seems to force everything in the entire repo to be on at least some level of consistent dependencies, and keeping go mod tidy happy likely requires go.work for anything.

Anyway, I'm not sure what the best solution is but at this point, stuff is so interdependent it seems very easy to break anything by changing something somewhere.  This does not seem ideal.

### CODE REVIEW

**Comment by etuleu** [comment]
Yea the dependence between models and worlds is not good. I actually don't find the separation useful anyway. I think we should create directories for each task like fworld, lvis, etc. and have separate helper packages, like network. The separate worlds+models makes it kind of hard to figure out which works with which also. I propose we reorganize a bit by task. Also in terms of python + go I think we should mix them in the same dir if they relate to the same task.

**Comment by garymm** [comment]
I will take a look at this soon and see if I can make bazel happy.
+1 for removing circular dependencies between modules.

**Comment by garymm** [comment]
I fixed bazel, but `go test` is broken in infra. I'll leave it to you to fix that.
Going forward if we have multiple incompatible versions in different directories, maintaining bazel will be harder but I think possible.

**Comment by rcoreilly** [comment]
I think unfortunately that these errors are due to the lack of a go.work file!  without that, it tries to use some version of models or agents or whatever from somewhere else.  So, again, this is due to the interdependencies among the repos.

In an ideal world, you would have separate repos for each of these, and you would commit a working version of worlds, then update go.mod in models to point to that, and everyone's happy.

and it really doesn't make sense to have infra be in the same repo as everything else.

@jedmccaleb can we fix this??

**Comment by garymm** [comment]
Well how's about we move towards a single go.mod file at the root of the repo for now. So at least we get rid of `go.work` and the submodules?

**Comment by jedmccaleb** [comment]
I'll move infra to its own repo. Why are worlds and models having issues? That seems like things aren't being done right.

**Review by garymm — APPROVED** [review]

**Pull request merged**
